repos:
-   repo: local
    hooks:
      - id: formatting
        name: format-code
        entry: bash -c 'black src/'
        language: system
        types: [python]
        always_run: true

      - id: linting
        name: lint-web
        entry: bash -c 'cd web && bun run lint'
        language: system
        types: [javascript, ts]
        always_run: true

      - id: formatting-web
        name: format-web
        entry: bash -c 'cd web && bun run format'
        language: system
        types: [javascript, ts, tsx]
        always_run: true

      - id: check-tests
        name: check-tests
        entry: bash -c 'python3 -m pytest'
        language: system
        types: [python]
        always_run: true
