services:
  redis:
    image: "redis:alpine"
  
  mongodb:
    image: "mongo:latest"
    volumes:
      - ./data:/data/db
    networks:
      - super-query
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    command: >
      sh -c "     
      uv run uvicorn src.main:app --workers 8 --host 0.0.0.0"
    volumes:
      - .:/app
    networks:
      - super-query


  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - super-query

networks:
  super-query:
