services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "     
      uvicorn src.main:app --host 0.0.0.0"
    volumes:
      - .:/app
    networks:
      - super-query

    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - backend
      networks:
        - super-query

networks:
  super-query:
