from typing import Optional
from pydantic import BaseModel, Field


class AIResponse(BaseModel):
    raw_response: str = Field(
        ...,
        description="The raw response from the AI model.",
    )
    sql_query: Optional[str] = Field(
        None, description="The SQL query generated by the AI"
    )
