name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Backend build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync 

      - name: Build and deploy
        run: |
          docker compose up -d
